CREATE TABLE IF NOT EXISTS books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  subtitle TEXT,
  creators TEXT,
  authors TEXT,
  translators TEXT,
  editors TEXT,
  illustrators TEXT,
  compilers TEXT,
  isbn TEXT,
  publisher TEXT,
  publication_place TEXT,
  publish_year TEXT,
  print_year TEXT,
  edition TEXT,
  volume TEXT,
  series_title TEXT,
  language TEXT,
  category TEXT,
  subjects TEXT,
  tags TEXT,
  call_number TEXT,
  cover_text TEXT,
  notes TEXT,
  cover_url TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);