-- AACR2-oriented bibliographic record (local IndexedDB + optional D1)
CREATE TABLE IF NOT EXISTS books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  main_entry TEXT,
  title TEXT NOT NULL,
  subtitle TEXT,
  parallel_title TEXT,
  creators TEXT,
  authors TEXT,
  translators TEXT,
  editors TEXT,
  illustrators TEXT,
  compilers TEXT,
  edition TEXT,
  publication_place TEXT,
  publisher TEXT,
  publish_year TEXT,
  copyright_date TEXT,
  print_year TEXT,
  extent TEXT,
  dimensions TEXT,
  accompanying_material TEXT,
  volume_number TEXT,
  series_title TEXT,
  series_number TEXT,
  added_entries TEXT,
  isbn TEXT,
  language TEXT,
  subjects TEXT,
  call_number TEXT,
  cover_text TEXT,
  notes TEXT,
  cover_url TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
